baseURL: https://iamsikun.github.io/sikun-blog
languageCode: en-us
title: Sikun's Blog
theme: PaperMod

params: 
  homeInfoParams: 
    Title: 'Hello'
    Content: 'Welcome to my blog'
  socialIcons: 
    - name: linkedin
      url: https://www.linkedin.com/in/sikun-xu-760685164/
    - name: github
      url: https://github.com/iamsikun
    - name: twitter
      url: https://twitter.com/sikun_xu
  ShowBreadCrumbs: true
  ShowReadingTime: true
  ShowShareButtons: true

menu: 
  main: 
    - identifier: tags
      name: Tags
      url: /tags/
      weight: 20
    - identifier: author
      name: Author
      url: https://www.sikunxu.com/
      weight: 30